name: comunicare con teams
on: push

jobs:
  team-comm:
    runs-on: ubuntu-latest # or your self-hosted runner if it exists
    steps:
      - uses: neonidian/teams-notify-build-status@v3
        with:
          webhookUrl: ${{ secrets.TEAMS_INCOMING_WEBHOOK_URL }}
          title: Titolo
          message: "ciao"
          shouldDisplayViewCommitButton: true
      - name: sent message
        run: echo "Messaggio inviato"
